const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#00B4D8",
    background: "#F5F8FF",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#5B5FEF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF0FF",
    secondaryForeground: "#3D3F8F",
    muted: "#EEF0FF",
    mutedForeground: "#6B7A99",
    accent: "#00B4D8",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDE1F0",
    input: "#DDE1F0",
    surface: "#FFFFFF",
    surfaceAlt: "#F0F2FF",
    tabBar: "#FFFFFF",
    userBubble: "#5B5FEF",
    aiBubble: "#FFFFFF",
    userBubbleText: "#FFFFFF",
    aiBubbleText: "#0D1B2A",
  },
  dark: {
    text: "#E8EEFF",
    tint: "#00D4AA",
    background: "#080D1A",
    foreground: "#E8EEFF",
    card: "#0F1729",
    cardForeground: "#E8EEFF",
    primary: "#7B7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2040",
    secondaryForeground: "#A0AACC",
    muted: "#1A2040",
    mutedForeground: "#6B7AA8",
    accent: "#00D4AA",
    accentForeground: "#080D1A",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#1E2A44",
    input: "#1E2A44",
    surface: "#0F1729",
    surfaceAlt: "#141E35",
    tabBar: "#0A1020",
    userBubble: "#7B7FFF",
    aiBubble: "#141E35",
    userBubbleText: "#FFFFFF",
    aiBubbleText: "#E8EEFF",
  },
  radius: 16,
};

export default colors;
